server:
  port: 8088
  servlet:
    context-path:
spring:
  redis:
    host: 192.168.188.128
    port: 6379
    password: 123
    #在主配置文件中，通过该参数指定激活哪一个环境的配置文件 （-xxx）
  #profiles:
   # active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/zy?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: mazhilong
    driver-class-name: com.mysql.jdbc.Driver
  data:
    solr:
      host: http://192.168.188.128:8088/solr
      repositories:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo
java0824:
  ma1: 马云
  ma2: 马化腾
  ma3: 马
ma1:
  i: 123
  name: 马云2
dubbo:
  application:
    name: demo
  registry:
    address: zookeeper://192.168.188.128:2181
  protocol:
    port: "20881"
